### ISSUE TITLE
你好，我注意到官方给了一个编译版本，你为什么又自己编译了一个呢😂

### ISSUE THREAD

**Issue by Looong01** [Mr-xiaobing/OpenposePlayGame#2]
我注意到官方给了一个编译版本https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases/tag/v1.7.0
你为什么又自己编译了一个呢

**Comment by Mr-xiaobing** [comment]
我尝试了一下，好像并不能直接使用。
